import Head from 'next/head'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Software and Design Consultancy by Teraret</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
<section>
    <h1>SOFTWARE AND DESIGN CONSULTANCY</h1>

    <p>
       Software and Design Consultancy by Teraret is focused on Artificial Intelligence, Big Data, Mobility, Device Creation, Software Engineering, and Design thinking.

        We believe in a high-quality workforce that delivers high-quality work and Profitable Enterprise.
    </p>

</section>
 <section>
        <h1>WHY CONSULT WITH US</h1>

        <p>
          In Sdc we believe every product and project needs a dedicated effort with Expert team members. We help your company Hire and Manage Expert teams Both OffShore and On Shore.

          Good Documentation is key for Success in any Digital Transformation Project.
        </p>
        <p>
        We also work in 24/7 Development and Support Model by hiring team Across Different Geographical location to help in Continuous Integration

        </p>

    </section>


<section>
     <h1>MICROSERVICES IS OUR GAME</h1>
    <p>Microservice Development is the Way to Build High Performace and Scalable Application. Software & Design Consultant Company has expertise in this Art of Building Microservices using Java, Python, Node & Other Programming Languages hence enabling AI, ML, BigData, Software Development, and Mobile Dev.</p>
 </section>
      </main>
    </div>
  )
}
