import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Software and Design Consultancy by Teraret</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Software and Design Consultancy
        </h1>

        <p className={styles.description}>
        Software and Design Consultancy by Teraret is focused on Artificial Intelligence, Big Data, Mobility, Device Creation, Software Engineering, and Design thinking.
We believe in a high-quality workforce that delivers high-quality work and Profitable Enterprise.
        </p>

        <div className={styles.grid}>
          <a href="/software-development" className={styles.card}>
            <h2>Sofware Development &rarr;</h2>
            {/* <p>Find in-depth information about Next.js features and API.</p> */}
          </a>

          <a href="/mobile-application-development" className={styles.card}>
            <h2>Mobile App &rarr;</h2>
            {/* <p>Learn about Next.js in an interactive course with quizzes!</p> */}
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Designing &rarr;</h2>
            {/* <p>Discover and deploy boilerplate example Next.js projects.</p> */}
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Machine Learning&rarr;</h2>
            {/* <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p> */}
          </a>
        </div>

        <h1 className={styles.title}>
        WHY CONSULT WITH US
        </h1>

        <p className={styles.description}>
        In Sdc we believe every product and project needs a dedicated effort with Expert team members. We help your company Hire and Manage Expert teams Both OffShore and On Shore.

Good Documentation is key for Success in any Digital Transformation Project.

​

We also work in 24/7 Development and Support Model by hiring team Across Different Geographical location to help in Continuous Integration
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://teraret.com"

          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
          <img src="/teraret.svg" alt="Teraret Logo" width={80} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
